# Generated by Django 3.2.7 on 2021-10-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211018_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='intro',
        ),
    ]
